#!/bin/bash

LOG_PATH="/build/twister-out/qemu_cortex_m3_ti_lm3s6965/zephyr_gnu/tests/hw_faults/simulation.i2c_hardware_fault/handler.log"

echo "=== 1. Initializing Zephyr Workspace ==="
# The zephyrprojectrtos/ci image already has QEMU, CMake, Python, and the SDK installed.
# We just need to pull in the Zephyr modules for this specific workspace.
west init -l .
west update
west zephyr-export
pip3 install -r scripts/requirements.txt

# echo "=== 2. Executing Build for QEMU ==="
# # We removed the 'host' toolchain override so Zephyr uses the container's built-in SDK cross-compilers.
# # Building the basic blinky sample for an emulated ARM Cortex-M3.
# # west build -b qemu_cortex_m3 samples/basic/blinky

echo "=== 3. Running QEMU Tests ==="
# Execute Twister targeting the QEMU ARM board. 
# Twister will automatically boot the QEMU VM, run the tests, parse the serial output, and shut it down.
west twister -p qemu_cortex_m3/ti_lm3s6965 -T tests/hw_faults -v

TWISTER_EXIT_CODE=$?

# If the test framework returns a non-zero exit code (failure/timeout)...
if [ $TWISTER_EXIT_CODE -ne 0 ]; then
    echo "WARNING: Twister suite reported a system anomaly."
    
    # Check if a crash log was generated by Zephyr/QEMU
    if [ -f "$LOG_PATH" ]; then
        echo "Invoking ESOps LLaMA Fault Detection Engine..."
        # Make sure dependencies like 'requests' are available in the container
        pip3 install requests --quiet
        python3 /build/esops_analyzer.py "$LOG_PATH" "Zephyr"
    else
        echo "No hardware handler log found to analyze."
    fi
    
    # Maintain pipeline integrity by exiting with the original failure code
    exit $TWISTER_EXIT_CODE
fi

echo "Run completed successfully."
